spring:
  application:
    name: security-security
  datasource:
    url: jdbc:h2:mem:security-security
    driverClassName: org.h2.Driver
    username: root
    password: root
#    url: jdbc:postgresql://localhost:5432/liquibase_example
#    username: postgres
#    driver-class-name: org.postgresql.Driver
#    password: pass
  liquibase:
    change-log: classpath:db/changelog/db.changelog.xml
  jpa:
    hibernate:
      naming:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create-drop
#      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
